/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111378-g13e9899014-20230708"
#endif /* AVUTIL_FFVERSION_H */
