/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1.3-14-ge5b5dd6653-20230708"
#endif /* AVUTIL_FFVERSION_H */
